### ISSUE TITLE
This is what I get when trying to compile. End result is that there's no 'revanced.apk' in the folder.

### ISSUE THREAD

**Issue by Harshey-zeRo** [Jarvis-Ank/Re-Vanced#13]
_brut.androlib.AndrolibException: Could not load resources.arsc from file: youtube.apk
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:788)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:66)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:58)
	at brut.androlib.Androlib.getResTable(Androlib.java:74)
	at app.revanced.patcher.Patcher.<init>(Patcher.kt:59)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:141)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)_

**Comment by Bartek20** [comment]
I'm currently working on a fix, but to make it work on an older version, you need to enter the id from the link to google drive or the link in the given format https://drive.google.com/file/d/[file id] (without /view?usp=sharing)
Despite the lack of a download error, it is precisely for this reason that the rest of the compilation fails

**Comment by Bartek20** [comment]
@Harshey-zeRo if you still have problems, you can use the ready fix from this [link](https://github.com/Bartek20/Re-Vanced/tree/priv) (until developer of this repository doesn't merge the patch to this repo)
