### ISSUE TITLE
[Bug]: Script finished with errors, no APK

### ISSUE THREAD

**Issue by jimmysofat6864** [Jarvis-Ank/Re-Vanced#26]
### What happened?

I ran the patch and I can't find the APK anywhere. It says patched with errors and I don't know why. 

### Logs (content of the /logs/app.log file)

[cmd.log](https://github.com/Jarvis-Ank/Re-Vanced/files/11256286/cmd.log)
[build.log](https://github.com/Jarvis-Ank/Re-Vanced/files/11256287/build.log)
[app (1).log](https://github.com/Jarvis-Ank/Re-Vanced/files/11256288/app.1.log)

This is what it shows in the collab window. 

<>:85: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:101: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:109: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:213: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:217: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:221: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:225: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:226: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:85: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:101: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:109: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:213: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:217: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:221: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:225: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:226: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-1-da8e4e903fd5>:85: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if mode is 'VERSION':
<ipython-input-1-da8e4e903fd5>:101: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif mode is 'APK':
<ipython-input-1-da8e4e903fd5>:109: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif mode is 'DOWNLOAD':
>>>>> >>>>> Startup variables <<<<< <<<<<
BUILDER_MODE: Google Drive
YOUTUBE_ID: https://drive.google.com/file/d/1gr1LNDTt61HTYE74XW0Pn5XA8ONdyht8/view?usp=sharing
INTEGRATIONS_TAG: LATEST
PATCHES_TAG: LATEST
CLI_TAG: LATEST
MICROG_URL: DEFAULT

[STEP 1/6] >>>>> >>>>> Creating working directories <<<<< <<<<<
[1/3] Logs folder
[2/3] Downloads folder
[3/3] ReVanced Folder

[STEP 2/6] >>>>> >>>>> Checking whether the system is up-to-date <<<<< <<<<<
[1/2] System update
[2/2] System upgrade

[STEP 3/6] >>>>> >>>>> Installing necessary apps <<<<< <<<<<
[1/2] gdown
[2/2] Zulu JDK-17

[STEP 4/6] >>>>> >>>>> Downloading necessary files <<<<< <<<<<
[1/5] Integrations
<ipython-input-1-da8e4e903fd5>:213: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if INTEGRATIONS_TAG is 'LATEST' or not check_tag('revanced-integrations', INTEGRATIONS_TAG): INTEGRATIONS_TAG = get_tag('revanced/revanced-integrations')
[2/5] Patches
<ipython-input-1-da8e4e903fd5>:217: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if PATCHES_TAG is 'LATEST' or not check_tag('revanced-patches', PATCHES_TAG): PATCHES_TAG = get_tag('revanced/revanced-patches')
[3/5] CLI
<ipython-input-1-da8e4e903fd5>:221: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if CLI_TAG is 'LATEST' or not check_tag('revanced-cli', CLI_TAG): CLI_TAG = get_tag('revanced/revanced-cli')
[4/5] MicroG
<ipython-input-1-da8e4e903fd5>:225: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if MICROG_URL is 'DEFAULT': MICROG_URL = 'https://github.com/Jarvis-Ank/Re-Vanced/blob/main/microG_0.2.24.220220.apk'
<ipython-input-1-da8e4e903fd5>:226: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if MICROG_URL is 'LATEST': MICROG_URL = get_tag('microg/GmsCore', True)
[5/5] Youtube

[STEP 5/6] >>>>> >>>>> Building revanced apk <<<<< <<<<<
INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Skipping custom-video-buffer: Excluded by default 
INFO: Skipping export-all-activities: Excluded by default 
INFO: Skipping predictive-back-gesture: Excluded by default 
INFO: Skipping remove-screenshot-restriction: Excluded by default 
INFO: Skipping spoof-wifi-connection: Excluded by default 
INFO: Merging ./ReVanced/revanced-integrations.apk 
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.jf.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:91)
	at lanchon.multidexlib2.RawDexIO.readRawDexFile(RawDexIO.java:53)
	at lanchon.multidexlib2.RawDexIO.readRawDexFile(RawDexIO.java:43)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:66)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:51)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:42)
	at lanchon.multidexlib2.MultiDexIO.readDexFile(MultiDexIO.java:36)
	at app.revanced.patcher.PatcherContext$Integrations.merge(PatcherContext.kt:35)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:339)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)

[STEP 6/6] >>>>> >>>>> Finishing <<<<< <<<<<
[1/2] Moving output file
mv: cannot stat './ReVanced/revanced.apk': No such file or directory
[2/2] Removing temporary files

[FINISHED] Script finished with errors, LOGS download'll start automaticaly within few seconds.

### Code of Conduct

- [X] I confirm and agree to contact me by pinging me in this thread in case of questions.

**Comment by BenCos17** [comment]
same for me also
